name: Codecov

on:
  - push

jobs:
  coverage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.10'

      - name: Generate coverage report
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)